util: Variant writer
zaeleus/noodles pull request #152
Opened 2023-03-04 17:12 UTC by malthesr

Closes #150 

The followup to #149, adding the `VariantWriter` trait in `noodles-vcf` and the `variant::Writer` in `noodles-util`.

As agreed in #150, I've left aside the issue of `StringMaps` in the impl for `VariantWriter` for now.

Mostly, this follows the implementation of `AlignmentWriter` and `alignment::Writer`, but I had to make a few choices about the compression behaviour for the BCF format that may warrant a bit of attention. Specifically,
- Specifying `None` for compression for BCF leads to a BGZF-compressed file using compression level 0.
- The default compression for BCF (and VCF) is `None`.
- The path extension `.bcf` leads to `None` for compression, unlike `.bcf.(gz|bgz)`.
As you mentioned in the previous PR, BCF should technically always be compressed, so I see how this could be debatable. Let me know if you have different preferences.

2023-03-04 17:14 UTC, malthesr commented on noodles-util/src/variant/writer/builder.rs
> +        let file = File::create(src)?;
My instinct would have been to wrap this in a `io::BufWriter`, but I didn't to mirror the `alignment::Writer`.

2023-03-06 21:37 UTC, zaeleus requested changes
> Specifying `None` for compression for BCF leads to a BGZF-compressed file using compression level 0.

`Some(None)` should write a raw BCF. Even though I think BCF should not be written raw, overriding this is confusing.

> The default compression for BCF (and VCF) is `None`.

The default compression for VCF should be uncompressed; and BCF, BGZF.

> The path extension `.bcf` leads to `None` for compression, unlike .`bcf.(gz|bgz)`.

As above, `bcf` should default to BGZF compression, not raw. Is `bcf.gz` a common suffix?

2023-03-08 16:17 UTC, malthesr commented
I'll get to this soon, just a few clarifications:

> As above, `bcf` should default to BGZF compression, not raw. 

That does make sense. Just to be clear, that means we're saying uncompressed BCF cannot be inferred from any path extension?

> Is `bcf.gz` a common suffix?

In the wild, I usually see `.bcf` to mean raw BCF, and `.bcf.gz` means compressed, so I see `.bcf.gz` more than `.bcf` but I can't say whether that's representative. Hopefully not, given how it's meant to be used. If we're never inferring uncompressed BCF from paths, then I think it makes sense to drop any support for `.bcf.gz`, so that the only special extensions are `.vcf`, `.vcf.{gz,bgz}`, and `bcf`.

2023-03-08 16:38 UTC, zaeleus commented
> Just to be clear, that means we're saying uncompressed BCF cannot be inferred from any path extension?

Correct.

> In the wild, I usually see `.bcf` to mean raw BCF, and `.bcf.gz` means compressed, so I see `.bcf.gz` more than `.bcf` but I can't say whether that's representative.

I'm curious what tooling is doing this. E.g., bcftool's inference doesn't support the `bcf.gz` suffix.

```
$ bcftools --version | head -1
bcftools 1.17
$ bcftools view --output simple.bcf simple.vcf
$ file simple.bcf
simple.bcf: Blocked GNU Zip Format (BGZF; gzip compatible), block length 1031
$ bcftools view --output simple.bcf.gz simple.vcf
$ file simple.bcf.gz
simple.bcf.gz: Variant Call Format (VCF) version 4.3, ASCII text
```

2023-03-08 16:46 UTC, malthesr commented
I'm not aware of any particular tooling doing it, I just see it as a convention to distinguish between compressed and uncompressed when piping output with `bcftools`. I think it arises because it somehow seems natural to distinguish between the four output modes `-O {v,z,u,b}` by path extension, and most people (like myself) are not aware that raw BCF is unofficial.

Either way, dropping any support `bcf.gz` seems to be the consistent way forward, and consumers can use the builder API to specify otherwise as needed.

2023-03-10 19:41 UTC, zaeleus approved these changes
Great, thanks for working on this!

2023-03-10 21:58 UTC, merged