Fasta index builder
zaeleus/noodles pull request #4
Opened 2020-09-16 22:29 UTC by slazicoicr

Would like input for

* Naming of structs/methods
* Module organization
* How indices should be constructed: `Vec<Record>` or an iterator that returns `Records`

2020-09-17 23:13 UTC, zaeleus requested changes
Currently, the index is simply a list of index records, i.e., `Vec<fai::Record>`. Ultimately, this is what should be returned, so we should focus on the public API being as simple as `pub fn index<P>(src: P) -> io::Result<Vec<fai::Record>> where P: AsRef<Path>`. This should be the only function that needs to be exposed at this point.

2020-09-19 18:45 UTC, slazicoicr commented
All changes are in. Public API suggestion makes sense and I can attempt them in a separate PR.

2020-09-21 22:12 UTC, zaeleus requested changes
* Add punctuation to short descriptions and comments.
* Avoid `unwrap` in examples and tests.
* Please include a public function in this changeset.

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai.rs
> +pub use self::{indexer::Indexer, reader::Reader, record::Record, writer::Writer};
```suggestion
pub use self::{reader::Reader, record::Record, writer::Writer};
```

As previously mentioned, `Indexer` should remain private.

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +    }
This can be replaced with a unit test for `len_with_right_trim`.

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +        let mut seq_len = self.read_sequence_line(&mut line)?.try_into().unwrap();
Please revert this (and others) to be consistent with the rest of the library.

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +        let data = b"ACGT\nNNNN";
```suggestion
        let data = b"ACGT\nNNNN\n";
```

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +use std::io;
Merge imports.

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +use memchr::memchr;
Separate imports into groups of std -> external -> crate -> super.

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +    R: io::BufRead,
```suggestion
    R: BufRead,
```

Import `std::io::BufRead`.

2020-09-21 22:12 UTC, zaeleus commented on noodles-fasta/src/fai/record.rs
> +#[derive(Debug, Default, PartialEq, Eq)]
```suggestion
#[derive(Debug, Default, Eq, PartialEq)]
```

2020-09-22 03:13 UTC, slazicoicr commented
All changes are in. The public function signature is `pub fn index<R: BufRead>(buf: R) -> Result<Vec<Record>, IndexError>`

2020-09-22 04:58 UTC, zaeleus commented
> `pub fn index<R: BufRead>(buf: R) -> Result<Vec<Record>, IndexError>`

This isn't quite the signature I envisioned previously.

Overall, the changes are okay for now. Instead of dragging this on, I can merge it as is and make stylization changes. Is this something you prefer, or do you want to do it via review suggestions?

2020-09-22 14:38 UTC, slazicoicr commented
I am happy to keep dinging at it. 

The suggestion from early on was `pub fn index<P>(src: P) -> io::Result<Vec<fai::Record>> where P: AsRef<Path>`, but I wasn't sure if that call should also be able to deal with `fasta.gz` files. The current signature can be turned private, as it can be used to deal with streams and in memory fasta sequences.

2020-09-23 00:17 UTC, zaeleus requested changes
Sorry for the large suggestion blocks; it seems GitHub doesn't show proper diffs for them. The changes are mainly stylization and wording.

2020-09-23 00:17 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +            return Err(IndexError::EmptyDefinition(self.offset));
If `length` is 0, doesn't that mean the sequence is empty and not the definition?

2020-09-23 00:17 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +use crate::record::definition::{Definition, ParseError};
```suggestion
use crate::{
    reader::{DEFINITION_PREFIX, NEWLINE},
    record::definition::{Definition, ParseError},
};
```

2020-09-23 00:17 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +        let mut end_line = false;
```suggestion
        let mut is_eol = false;
```

2020-09-23 00:17 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +            if end_line || reader_buf.is_empty() || reader_buf[0] == DEFINITION_PREFIX {
```suggestion
            if is_eol || reader_buf.is_empty() || reader_buf[0] == DEFINITION_PREFIX {
```

2020-09-23 00:17 UTC, zaeleus commented on noodles-fasta/src/fai/indexer.rs
> +                    end_line = true;
```suggestion
                    is_eol = true;
```

2020-09-23 00:18 UTC, zaeleus commented
> I wasn't sure if that call should also be able to deal with `fasta.gz` files.

Indexing a compressed FASTA isn't useful without an associated bgzip index (gzi), which is out of scope for this patch.

2020-09-24 00:24 UTC, slazicoicr commented
Question about `pub fn index<P>(src: P) -> io::Result<Vec<fai::Record>> where P: AsRef<Path>` testing approach. Would it be necessary to include a (small) .fasta file to load during doc string testing (if so, where is the spot for it)?

Another approach is to keep (and rename) `fn index_from_bufread<R: BufRead>(buf: R) -> Result<Vec<Record>, IndexError>` (no longer public) and have tests done on it. The public file path `index` function would just be a simple extension of `index_from_bufread`.

The last option is not to do any testing with `pub fn index<P>(src: P) -> io::Result<Vec<fai::Record>> where P: AsRef<Path>`, as it is fairly simple function.

2020-09-24 03:26 UTC, zaeleus commented
You can add an example to test compilation and not run it. This can be done with the [`no_run` attribute](https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes) on a code block. For example, https://github.com/zaeleus/noodles/blob/0cbea550aa5cf2710a92fa947f428de07fd0fa3d/noodles-fasta/src/lib.rs#L33-L53

2020-09-25 02:29 UTC, slazicoicr commented
Public `index` function now takes a file path.

2020-09-26 21:14 UTC, zaeleus commented
Nice, thanks!

2020-09-26 22:54 UTC, slazicoicr commented
Anything left for this PR?

2020-09-26 23:24 UTC, zaeleus approved these changes

2020-09-27 01:10 UTC, slazicoicr commented
Don't have permissions to merge.

2020-09-27 03:47 UTC, zaeleus commented
Yes, please have patience, @slazicoicr; it will be merged. :)

2020-09-29 00:03 UTC, merged